/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f1f3ff",
        "on-secondary-fixed-variant": "#003ea8",
        "on-tertiary-container": "#339650",
        "secondary": "#0051d5",
        "secondary-container": "#316bf3",
        "surface-tint": "#565e74",
        "on-primary-fixed": "#131b2e",
        "on-secondary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "on-surface-variant": "#45464d",
        "background": "#f9f9ff",
        "inverse-primary": "#bec6e0",
        "surface-container-high": "#e1e8fd",
        "primary-container": "#131b2e",
        "on-background": "#141b2b",
        "primary": "#000000",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#dae2fd",
        "outline": "#76777d",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#95f8a7",
        "surface-variant": "#dce2f7",
        "on-error-container": "#93000a",
        "surface": "#f9f9ff",
        "surface-container": "#e9edff",
        "outline-variant": "#c6c6cd",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#edf0ff",
        "on-primary-container": "#7c839b",
        "on-surface": "#141b2b",
        "on-tertiary-fixed": "#00210a",
        "surface-bright": "#f9f9ff",
        "on-tertiary-fixed-variant": "#005323",
        "surface-container-highest": "#dce2f7",
        "inverse-surface": "#293040",
        "on-primary-fixed-variant": "#3f465c",
        "primary-fixed-dim": "#bec6e0",
        "tertiary-fixed-dim": "#79db8d",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#fefcff",
        "on-secondary": "#ffffff",
        "surface-dim": "#d3daef",
        "tertiary-container": "#00210a",

        // Compatibility aliases with existing theme
         bg: "rgb(var(--c-bg) / <alpha-value>)",
         surface: "rgb(var(--c-surface) / <alpha-value>)",
         content: "rgb(var(--c-text) / <alpha-value>)",
         muted: "rgb(var(--c-muted) / <alpha-value>)",
         border: "rgb(var(--c-border) / <alpha-value>)",
         elevated: "rgb(var(--c-elevated) / <alpha-value>)",
         primary: "rgb(var(--c-primary) / <alpha-value>)",
         "primary-fg": "rgb(var(--c-primary-fg) / <alpha-value>)",
         accent: "rgb(var(--c-accent) / <alpha-value>)",
         justified: "rgb(var(--c-justified) / <alpha-value>)",
         caution: "rgb(var(--c-caution) / <alpha-value>)",
         danger: "rgb(var(--c-danger) / <alpha-value>)",
         info: "rgb(var(--c-info) / <alpha-value>)",
         hazard: {
           pothole: "rgb(var(--c-hazard-pothole) / <alpha-value>)",
           speedbreaker: "rgb(var(--c-hazard-speedbreaker) / <alpha-value>)",
           waterlogging: "rgb(var(--c-hazard-waterlogging) / <alpha-value>)",
           debris: "rgb(var(--c-hazard-debris) / <alpha-value>)",
         },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-xs": "0.5rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "nav-bottom-height": "4rem",
        "gutter-screen": "1rem",
        "space-lg": "1.25rem",
        "space-2xs": "0.25rem",
        "appbar-height": "3.5rem",
        "touch-target-min": "3rem",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "display-sm": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "numeric-metric": ["Manrope", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-md": ["Manrope", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "display-sm": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "numeric-metric": ["24px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
      },
       boxShadow: {
         card: "0 1px 4px rgba(0,0,0,0.18), 0 8px 24px rgba(0,0,0,0.12)",
         glow: "0 0 0 1px rgb(var(--c-primary) / 0.35), 0 0 24px -4px rgb(var(--c-primary) / 0.3)",
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(14px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.92)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.7)", opacity: "0.7" },
          "80%, 100%": { transform: "scale(2.2)", opacity: "0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out both",
        "fade-up": "fade-up 0.5s cubic-bezier(0.22,1,0.36,1) both",
        "scale-in": "scale-in 0.4s cubic-bezier(0.22,1,0.36,1) both",
        "pulse-ring": "pulse-ring 2s cubic-bezier(0.4,0,0.6,1) infinite",
        float: "float 3.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
