import { useParams } from "react-router-dom";
import { ScreenHeader } from "@/components/layout/ScreenHeader";
import { SchematicMap } from "@/components/map/SchematicMap";
import { RoadEventCard } from "@/components/road/RoadEventCard";
import { Card } from "@/components/ui/Card";
import { Icon } from "@/components/ui/Icon";
import { useRoadEvents } from "@/hooks/queries";
import { ROAD_EVENT_LABEL } from "@/config/labels";
export function RoadEventScreen() { const { id } = useParams<{ id: string }>(); const { data: roadEvents = [], isLoading, error } = useRoadEvents(); const event = roadEvents.find((e) => e.id === id); if (!isLoading && !event) return <div className="flex flex-col"><ScreenHeader title="Hazard" back /><div className="mt-16 text-center"><Icon name="TriangleAlert" className="mx-auto h-8 w-8 text-muted" /><p className="mt-2 text-sm text-muted">{error ? "Unable to load this hazard right now." : "This hazard no longer exists."}</p></div></div>; if (!event) return <div className="flex flex-col"><ScreenHeader title="Hazard" back /><p className="p-4 text-sm text-muted">Loading…</p></div>; return <div className="flex flex-col"><ScreenHeader title={ROAD_EVENT_LABEL[event.type]} subtitle="Shared road intelligence" back /><div className="flex flex-col gap-4 p-4 pb-8"><div className="relative h-[220px] overflow-hidden rounded-2xl hairline"><SchematicMap roadEvents={[event]} highlightId={event.id} showRoute={false} className="absolute inset-0" /></div><RoadEventCard event={event} highlight /><Card padded={false} className="divide-y divide-border/60"><DetailRow icon="Clock" label="First detected" value={event.firstDetected} /><DetailRow icon="Clock" label="Last confirmed" value={event.lastConfirmed} /><DetailRow icon="Users" label="Distinct riders" value={String(event.riders)} /><DetailRow icon="Activity" label="Total reports" value={String(event.reports)} /><DetailRow icon="MapPin" label="Location" value={`${event.latitude.toFixed(4)}, ${event.longitude.toFixed(4)}`} /></Card><div className="rounded-xl bg-primary/[0.06] p-3.5 ring-1 ring-inset ring-primary/20"><div className="flex gap-2.5"><Icon name="Sparkles" className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><p className="text-xs leading-relaxed text-muted">This hazard's confidence grows as more riders independently confirm it — turning individual manoeuvres into shared road intelligence.</p></div></div></div></div>; }
function DetailRow({ icon, label, value }: { icon: string; label: string; value: string }) { return <div className="flex items-center justify-between px-4 py-3"><span className="inline-flex items-center gap-2 text-sm text-muted"><Icon name={icon} className="h-4 w-4" />{label}</span><span className="tnum text-sm font-semibold text-content">{value}</span></div>; }
