import { ScreenHeader } from "@/components/layout/ScreenHeader";
import { Card } from "@/components/ui/Card";
import { Icon } from "@/components/ui/Icon";
import { ProgressRing } from "@/components/ui/ProgressRing";
import { useScoreStore } from "@/store/scoreStore";
import { BASE_SCORE } from "@/engine/scoreEngine";
import { cn } from "@/lib/cn";
function trustLabel(score: number): string { if (score >= 85) return "Trusted rider"; if (score >= 70) return "Building trust"; return "New rider"; }
export function ScoreScreen() { const factors = useScoreStore((s) => s.factors); const score = useScoreStore((s) => s.score); return <div className="flex flex-col"><ScreenHeader title="Vouch Score" subtitle="Contextual riding behaviour" /><div className="flex flex-col gap-5 p-4 pb-8"><Card glow className="flex flex-col items-center py-6"><ProgressRing value={score} size={168} stroke={13}><div className="text-center"><div className="tnum text-5xl font-extrabold text-content">{score}</div><div className="text-xs font-semibold uppercase tracking-wide text-muted">out of 100</div></div></ProgressRing><div className="mt-4 inline-flex items-center gap-2 rounded-full bg-primary/15 px-3.5 py-1.5 text-sm font-bold text-primary ring-1 ring-primary/30"><Icon name="ShieldCheck" className="h-4 w-4" />{trustLabel(score)}</div></Card><div><h2 className="mb-2 text-sm font-bold text-content">How it's calculated</h2><Card padded={false} className="divide-y divide-border/60"><Row label="Base score" value={BASE_SCORE} muted />{factors.map((f) => <Row key={f.key} label={f.label} value={f.delta} delta />)}<div className="flex items-center justify-between px-4 py-3.5"><span className="font-bold text-content">Total</span><span className="tnum text-lg font-extrabold text-primary">{score}</span></div></Card></div><div className="rounded-xl bg-white/[0.03] p-3.5 hairline"><div className="flex gap-2.5"><Icon name="Info" className="mt-0.5 h-4 w-4 shrink-0 text-muted" /><p className="text-xs leading-relaxed text-muted">The Vouch Score is a concept demonstration of contextual riding behaviour. It is <span className="font-semibold text-content">not</span> an insurance, legal, credit, or official safety score.</p></div></div></div></div>; }
function Row({ label, value, delta, muted }: { label: string; value: number; delta?: boolean; muted?: boolean }) { const positive = value > 0; const sign = delta ? (positive ? "+" : "") : ""; return <div className="flex items-center justify-between px-4 py-3.5"><span className={cn("text-sm", muted ? "text-muted" : "text-content")}>{label}</span><span className={cn("tnum text-sm font-bold", !delta && "text-content", delta && positive && "text-justified", delta && !positive && "text-danger")}>{sign}{value}</span></div>; }
